#!/bin/bash

COMMAND=$1
CLI_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

case $COMMAND in
  build)
    SCRIPT="build.sh"
    ;;
  test)
    SCRIPT="runTests.sh"
    ;;
  repl)
    SCRIPT="wrepl.sh"
    # Allow REPL to run without any file
    if [ -z $3 ] ; then
      set -- "${@:1:2}" "$CLI_DIR/includes/emptyFile.wlk" "${@:4}"
    fi
    ;;
  run)
    SCRIPT="runPrograms.sh"
    ;;
  check)
    SCRIPT="wchecker.sh"
    ;;
  ast)
    SCRIPT="wast.sh"
    ;;
  format)
    SCRIPT="wformat.sh"
    ;;
  *)
    echo "El comando 'wollok $COMMAND' no existe."
    echo
    echo "Esta es una lista de comandos que podés ejecutar con wollok"
    echo "build            => valida archivos .wlk en la carpeta actual"
    echo "test             => ejecuta todos los archivos de tests en la carpeta actual"
    echo "run              => ejecuta todos los archivos de programas en la carpeta actual"
    echo "repl archivo.wlk => ejecuta la consola REPL (el archivo es opcional)"
    echo "format aves.wlk  => aplica el formateador al archivo aves.wlk (-save actualiza el archivo)"
    echo "check archivo    => compila y valida un archivo con extensión Wollok válida"
    echo "ast archivo      => devuelve un JSON el AST del archivo según la gramática de Wollok"
    echo 
    echo "Para probar cambios en el ambiente local de desarrollo de Wollok XText," \
      "se debe definir la variable WOLLOK_DEV_ROOT apuntando al repositorio principal de wollok-xtext."
    echo 
    echo "Por ejemplo: "
    echo "$ WOLLOK_DEV_ROOT=../xtext wollok test"
    echo
    echo "Opciones: "
    echo "  -dontValidate: Evita que se ejecuten las validaciones de wollok. "
    echo "                 (Necesario al correr los sanity tests porque algunos incluyen programas intencionalmente erróneos.)"
    exit 1
    ;;
esac

shift
source $CLI_DIR/$SCRIPT "$@"
